apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: hello-world
  name: hello-world
  namespace: default
spec:
  replicas: 10
  selector:
    matchLabels:
      app: hello-world
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: 880101261/hello-world
        name: hello-world-service
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world
  name: hello-world
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: hello-world
  sessionAffinity: None
  type: LoadBalancer
  externalIPs:
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
metadata:
  labels:
    app: hello-world
  name: hello-world
  namespace: default
nodeRegistration:
  kubeletExtraArgs:
    cloud-provider: aws
